Name: PYPI_API_TOKEN
Value: pypi-AgEIcHlwaS5vcmcCJDQxMTQ1MTY3LTljZDAtNGI4OS05MDFiLWYwNTgxZDMyZTlmZgACKlszLCIyOTU3YmJmNS0wZmYxLTQ1YWYtOGRiYi0wZGU2NDE4NTFmN2UiXQAABiAswiOVsw9dZ35fo6y1zsv_5emtfSJ8_hsu44jYJLQpOw
